#! /bin/sh
$HOME/.scripts/custom-autostart
xsetroot -cursor_name left_ptr
picom&
dunst&
xset -dpms s off & # disable screen blanking
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
nitrogen --restore
wmname LG3D &

xrandr --output HDMI-1 --primary --left-of HDMI-0

bspc config window_gap          20
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

$HOME/.config/bspwm/autostart

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a XTerm state=floating
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a discord state=floating center=on rectangle=1600x900+0+0
bspc rule -a kitty state=floating center=on rectangle=900x600+0+0
bspc rule -a thunderbird state=floating center=on rectangle=1600x900+0+0
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
setxkbmap -layout de

pgrep bspswallow || nohup ~/.scripts/bspswallow &
$HOME/.config/polybar/zodd/launch.sh &
feh --bg-scale ~/Pictures/peakpx.jpg --bg-scale ~/Pictures/walking_here.jpg

bspc rule -a \* -o state=floating && sleep 0.015 ; kitty -e $SHELL -c "$HOME/.config/neofetch/launch-neofetch.sh && $SHELL" &
# Start firefox
/bin/bash -c "bspc desktop -f '^2' --follow ; bspc rule -a \* -o node=@$(bspc query -D -d):.focused split_dir=south follow=off ; firefox file:///home/$USER/.config/startpage/index.html &" &
bspc desktop -f '^2' --follow &

xinput set-prop "SOAI USB Gaming Mouse" "libinput Accel Speed" -0.5
timedatectl&
xset dpms 0
setxkbmap -option caps:escape # Caps lock -> escape
bashrun2 hide&
nohup rule_away > /dev/null 2>&1 &

export PATH=$PATH:~/bin
export PATH=$PATH:~/.local/bin
export XDG_CONFIG_HOME=~/.config
